# Github Actions script to produce binary wheels.
#
# * One build to create all wheels (cross-platform universal wheel).
# * One build (with matrix) test the wheels on a selection of platforms.
# * One build to publish the wheels on GitHub and Pypi.

name: CD

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-source:
    name: Build all wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-tags: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Display Python version
        run: python3 -c "import sys; print(sys.version)"
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools flit build twine hatchling wheel
          pip install -U  numpy==1.26 scikit-build-core hatch-build-scripts pybind11_stubgen scikit-build
      - name: Install APT On Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install -qq -y libglu1-mesa build-essential ninja-build libeigen3-dev
      - name: Build wheel
        run: |
          python -m build -n -s
      - name: Twine check
        run: |
          twine check dist/*
      - name: Upload source distributions
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: all_wheels
  build-wheels:
    name: Build all wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9, '3.10', '3.11', '3.12']
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-tags: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version}}
      - name: Display Python version
        run: python3 -c "import sys; print(sys.version)"
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools flit build twine hatchling wheel
          pip install -U  numpy==1.26 scikit-build-core hatch-build-scripts pybind11_stubgen scikit-build
      - name: Install APT On Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install -qq -y libglu1-mesa build-essential ninja-build libeigen3-dev
      - name: Install Brew On Mac OS
        if: matrix.os == 'macos-14' || matrix.os == 'macos-13'
        run: |
          brew install eigen cmake ninja
      - name: Build wheel
        run: |
          python -m build -n -w
      - name: Twine check
        run: |
          twine check dist/*
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: wheel-${{ matrix.os }}-${{ matrix.python-version }}

  publish:
    name: Publish to Github and Pypi
    runs-on: ubuntu-latest
    needs: [build-wheels]
    if: success() && startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Download assets
      uses: actions/download-artifact@v5
      with:
        path: dist
    - name: Flatten dist dir
      run: |
        find dist -mindepth 2 -type f -exec mv -f '{}' dist/ ';'
        rm -rf dist/*/
    - name: Set version from git ref
      run: echo "PYCLIPR_PY_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.PYCLIPR_PY_VERSION }}
        name: ${{ env.PYCLIPR_PY_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
            dist/*.tar.gz
            dist/*.whl
        body: |
            Autogenerated wheels for Pyclipr
        draft: false
        prerelease: false
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}